"""Compatibility shim: recreate `langchain_community.chat_models.vertexai`.

WHY: langchain-community 0.4.x removed `chat_models/vertexai.py` (the package
is being sunset per https://github.com/langchain-ai/langchain-community/issues/674).
Ragas 0.4.3 still imports `ChatVertexAI` from that path, so without this shim
`import ragas` raises `ModuleNotFoundError`.

The fix is to re-export `ChatVertexAI` from the official migration target,
`langchain-google-vertexai`. We write a one-line shim file into the installed
`langchain_community` package. `uv sync` may overwrite it; run this script
after any reinstall that touches langchain-community.

Usage:
    uv run python scripts/patch_langchain_vertexai_shim.py
"""

from __future__ import annotations

import sys
from pathlib import Path

SHIM_BODY = '''\
"""Compatibility shim. Regenerated by scripts/patch_langchain_vertexai_shim.py.

langchain-community 0.4+ removed `chat_models.vertexai`. Ragas 0.4.3 still
imports `ChatVertexAI` from that path, so we re-export it from the official
migration target `langchain-google-vertexai`.
"""
from langchain_google_vertexai.chat_models import ChatVertexAI

__all__ = ["ChatVertexAI"]
'''


def main() -> int:
    try:
        import langchain_community
    except ImportError:
        print("[FAIL] langchain_community is not installed; nothing to patch.", file=sys.stderr)
        return 1
    try:
        import langchain_google_vertexai  # noqa: F401
    except ImportError:
        print(
            "[FAIL] langchain-google-vertexai is not installed. "
            "Run `uv sync --extra eval` first.",
            file=sys.stderr,
        )
        return 1

    chat_dir = Path(langchain_community.__file__).parent / "chat_models"
    chat_dir.mkdir(parents=True, exist_ok=True)
    shim_path = chat_dir / "vertexai.py"
    shim_path.write_text(SHIM_BODY, encoding="utf-8")
    print(f"[OK] wrote shim to {shim_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
